import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import {QueryProvider} from '@/lib/query-provider';
import {NavBar} from '@/components/navbar/navbar';
import {auth} from '@/auth';
import {SessionProvider} from 'next-auth/react';
import {Footer} from '@/components/footer/footer';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Hitohito Tadano',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="es">
        <body className={inter.className} suppressHydrationWarning={true}>
          <NavBar />
          <QueryProvider>{children}</QueryProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
