import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import {ClerkProvider} from '@clerk/nextjs';
import {QueryProvider} from '@/lib/query-provider';
import {NavBar} from '@/components/navbar/navbar';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Hitohito Tadano',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <ClerkProvider>
        <body className={inter.className}>
          <NavBar />
          <QueryProvider>{children}</QueryProvider>
        </body>
      </ClerkProvider>
    </html>
  );
}
