import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import {QueryProvider} from '@/lib/query-provider';
import {NavBar} from '@/components/navbar/navbar';
import {auth} from '@/auth';
import {SessionProvider} from 'next-auth/react';
import DictionaryProvider from '@/lib/dictionary-provider';
import {getDictionary} from '@/actions/dictionary';
import { Locale } from '@/i18n.config';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Hitohito Tadano',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: {lang, locale},
}: Readonly<{
  children: React.ReactNode;
  params: {lang: Locale; locale: string};
}>) {
  const session = await auth();
  const dictionary = await getDictionary(lang);

  return (
    <SessionProvider session={session}>
      <html lang={locale}>
        <DictionaryProvider dictionary={dictionary}>
          <body className={inter.className}>
            <NavBar />
            <QueryProvider>{children}</QueryProvider>
          </body>
        </DictionaryProvider>
      </html>
    </SessionProvider>
  );
}
